### ISSUE TITLE
error while building inside docker

### ISSUE THREAD

**Issue by iraizo** [gornostay25/svelte-adapter-bun#35]
Hello, I've tried to build my sveltekit project inside a dockerfile but stumbled onto an unimplemented function (is what it seems like?)

```
 > [5/5] RUN bun run build:
2.815 > Using svelte-adapter-bun
2.828 error during build:
2.828 TypeError: undefined is not a function (near '...zlib.createBrotliCompress...')
2.828     at <anonymous> (/home/bun/app/node_modules/svelte-adapter-bun/index.js:144:18)
2.828     at compress_file (/home/bun/app/node_modules/svelte-adapter-bun/index.js:142:14)
2.828     at <anonymous> (/home/bun/app/node_modules/svelte-adapter-bun/index.js:133:2)
2.828     at map (:1:11)
2.828     at <anonymous> (/home/bun/app/node_modules/svelte-adapter-bun/index.js:133:2)
2.828     at processTicksAndRejections (:61:39)
2.852 error: script "build" exited with code 1 (SIGHUP)
```

This only happens when toggling the brotli precompression on, (for some reason it works on my local machine?) It seems like the Bun documentation also states that `zlib.createBrotliCompress` is [unimplemented](https://bun.sh/docs/runtime/nodejs-apis#node-zlib), I've also searched for the function inside the source code of Bun itself and only found type definitions for it.

**Comment by Baehn** [comment]
same problem here,  installing nodejs in my container solved it which is probably also explaining why it is working on your local machine

**Comment by iraizo** [comment]
> same problem here, installing nodejs in my container solved it which is probably also explaining why it is working on your local machine

I just fixed it temporarily by disabling brotli
