### ISSUE TITLE
 TypeErrorserver.websocket

### ISSUE THREAD

**Issue by peterlerche** [gornostay25/svelte-adapter-bun#38]
Hi,

I am getting this error when running bun 1.0.9 together with svelte-adapter-bun 0.5.1.
Any idea what is causing this fault?
 
bun run ./dist/index.js
Fail: websocket handler error: 743 |   function defaultAcceptWebsocket(request, upgrade) {
744 |     return upgrade(request);
745 |   }
746 |   try {
747 | 
748 |     const handleWebsocket = server.websocket();
                               ^
TypeError: server.websocket is not a function. (In 'server.websocket()', 'server.websocket' is undefined)
      at handler_default (./dist/index.js:748:28)
      at ./dist/index.js:773:32

Listening on 0.0.0.0:3000

svelte.config.js
    adapter: adapter({
            out: "dist",
           assets: true,
            envPrefix: "",
            development: false,
                      precompress: {
                brotli: false,
                gzip: true,
            },
            dynamic_origin: true,
            xff_depth: 1,
        }),

**Comment by peterlerche** [comment]
Just tested with the new version of bun 1.0.10 and the problem persists.

**Comment by mragil** [comment]
did you found the solution for this?
