### ISSUE TITLE
SvelteKit demo app not working

### ISSUE THREAD

**Issue by peterlerche** [gornostay25/svelte-adapter-bun#39]
Desperate to find a solution to #38 I made a clean installation of Svelte demo app using the guide on https://bun.sh/guides/ecosystem/sveltekit. 

When browsing the demo app, I get a lot of the below faults.  

709 |   });
710 | };
711 | var get_origin = function(headers) {
712 |   const protocol = protocol_header && headers.get(protocol_header) || "https";
713 | 
714 |   const host = headers.get(host_header);
                  ^
TypeError: Invalid header name: ''
      at get_origin (/my-app/build/index.js:714:15)
      at ssr (/my-app/build/index.js:682:23)

Why do we see these faults, is Bun changing their internals or is svelte-adapter-bun out of sync with the newer version of bun?  

All help, ideas, and guidance will be appreciated.

**Comment by Dan1ve** [comment]
I have the same problem in a "real" application, not just the demo.

**Comment by Dan1ve** [comment]
Until this has been merged, it seems a fix is to set the following env variables:

``` 
PROTOCOL_HEADER=x-forwarded-proto
HOST_HEADER=x-forwarded-host
``

**Comment by catdadcode** [comment]
I've forked this repo and published my own NPM package. The fix for this issue is already merged into my fork and I plan to keep it updated.

```zsh
bun add @catdadcode/svelte-adapter-bun
```

https://github.com/catdadcode/svelte-adapter-bun
